### ISSUE TITLE
好好的项目，装了你的插件build错误；卸载之后仍然build错误。

### ISSUE THREAD

**Issue by aardpro** [liuxiaoy/cordova-plugin-tbs-webview#1]
BUILD FAILED in 3s

> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE

> Task :app:processDebugManifest FAILED

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

22 actionable tasks: 3 executed, 19 up-to-date
D:\cordova\EPC\platforms\android\gradlew: Command failed with exit code 1 Error output:
D:\cordova\EPC\platforms\android\app\src\main\AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 15 cannot be smaller than version 19 declared in library [:CordovaLib] D:\cordova\EPC\platforms\android\CordovaLib\build\intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 15
        Suggestion: use a compatible library with a minSdk of at most 15,
                or increase this project's minSdk version to at least 19,
                or use tools:overrideLibrary="org.apache.cordova" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 19 declared in library [:CordovaLib] D:\cordova\EPC\platforms\android\CordovaLib\build\intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 15
        Suggestion: use a compatible library with a minSdk of at most 15,
                or increase this project's minSdk version to at least 19,
                or use tools:overrideLibrary="org.apache.cordova" to force usage (may lead to runtime failures)

**Comment by liuxiaoy** [comment]
一般可以这样解决
```
rm -r platforms plugins
cordova prepare android
```
