### ISSUE TITLE
application error net::ERR_CONNECTION_REFUSED (https://localhost/index.html)

### ISSUE THREAD

**Issue by nightost** [liuxiaoy/cordova-plugin-tbs-webview#11]
使用此plugin打包需要额外配置么，打包debug大小才8M

打开应用程序报错

application error net::ERR_CONNECTION_REFUSED (https://localhost/index.html)

打包环境：android 10.1
cordova:  11.0.0
gradle: 8.0

运行环境
android 7.0.0

**Comment by liuxiaoy** [comment]
动态集成的话，包大小只增加几百KB，静态集成的是增加几十MB。不需要额外的手动配置。
请确认下地址是否正确。比如协议用的是https，端口用的是443？
