### ISSUE TITLE
怎么升级静态集成包？

### ISSUE THREAD

**Issue by yuanxu** [liuxiaoy/cordova-plugin-tbs-webview#2]
非常感谢大侠的工作，帮我们解决大问题！
我们想升级到tbs 5.2，请教怎么更新x5core.aar？

**Comment by liuxiaoy** [comment]
静态集成的版本对应 chrome 66，目前还没有新的版本放出来。

**Comment by yuanxu** [comment]
这个静态集成包怎么拿到的？
可以自己提取内核，通过更新相关文件升级x5core.aar实现升级吗？

**Comment by liuxiaoy** [comment]
理论上可以，这里用的是从官方qq群提供的x5core.aar包。
如果你有新的x5core.aar可以提pr。
用gradle方式引入就更好了。

**Comment by yuanxu** [comment]
好的。谢谢~ 有时间试试看
