### ISSUE TITLE
请问tbs_sdk_thirdapp_*.jar这个jar包的作用是什么，为什么新版去掉了这个文件

### ISSUE THREAD

**Issue by haohetao** [liuxiaoy/cordova-plugin-tbs-webview#6]
这个文件是用来共享第三方app下载的x5内核的吗

**Comment by liuxiaoy** [comment]
这个文件就是sdk，但是不包含x5内核本身。新版中这个文件被包含在so库里了。

**Comment by haohetao** [comment]
so库不是也删了吗，so不是说开32位模式用的吗

**Comment by haohetao** [comment]
@liuxiaoy 
0.2.1版本中没有所谓的so库

**Comment by liuxiaoy** [comment]
> 这个文件就是sdk，但是不包含x5内核本身。新版中这个文件被包含在so库里了。

是aar库，说错了。

**Comment by haohetao** [comment]
> 
> 
> > 这个文件就是sdk，但是不包含x5内核本身。新版中这个文件被包含在so库里了。
> 
> 是aar库，说错了。

0.3版本有静态的aar库，但是0.2.1版本并没有呀

**Comment by liuxiaoy** [comment]
0.2.x和0.1.x不是静态方案，是动态下载x5内核的。那个jar就是sdk 。
0.3.x是静态方案，打包了x5内核。

**Comment by liuxiaoy** [comment]
0.2.1 使用了gradle方式引入sdk

**Comment by haohetao** [comment]
@liuxiaoy 
thanks
