### ISSUE TITLE
荣耀的pad， 安装了apk,  不起效果？

### ISSUE THREAD

**Issue by qiutian00** [liuxiaoy/cordova-plugin-tbs-webview#7]
已在项目的MainApplication或MainActivity`的onCreate``方法内，增加以下代码：
```
QbSdk.initX5Environment(this, null);
```
测试还是老版本的webview
![image](https://user-images.githubusercontent.com/24382500/110318798-ee5cec80-8048-11eb-836f-5ae3b37d54d4.png)

**Comment by liuxiaoy** [comment]
用的哪个版本

**Comment by qiutian00** [comment]
插件版本：cordova-plugin-tbs-webview 0.1.6 
![image](https://user-images.githubusercontent.com/24382500/110420553-6fae9080-80d6-11eb-8c9e-f7a51fa5d752.png)
cordvov 平台版本：
![image](https://user-images.githubusercontent.com/24382500/110420590-8f45b900-80d6-11eb-88d6-15bfe9fc2611.png)

**Comment by liuxiaoy** [comment]
检查配置，另外首次启动需要下载内核，下载成功会在后续使用时启用x5内核。着急解决问题可以站内或者看我邮箱前那串数字

**Comment by qiutian00** [comment]
噢噢。我再看看。谢谢回复。
