### ISSUE TITLE
华为手机android10使用0.2.1插件x5内核不加载

### ISSUE THREAD

**Issue by haohetao** [liuxiaoy/cordova-plugin-tbs-webview#8]
cordova用的是最新正式版
同样环境我用uniapp打包的x5就是可以用的

**Comment by haohetao** [comment]
我用0.3.1可以成功加载，但是这时apk包已经达到近一百兆了。

**Comment by haohetao** [comment]
可以了，只是下载比较慢，不是说可以与微信共享的吗，为啥装的有微信每次还是要重新下载x5

**Comment by haohetao** [comment]
另外希望开启非wifi网络下载

**Comment by haohetao** [comment]
反复测试了很多遍，使用0.2.1时每次重新安装后首次启动x5都会加载失败，即使以前加载成功过

**Comment by haohetao** [comment]
是否可以考虑app首次启动时加一个延迟等待X5的初始化,我猜是onCreate方法里面启动webView和x5初始化几乎是同时执行的，如果让webView推后加载或许能解决这个问题，1秒钟也好。

**Comment by liuxiaoy** [comment]
@haohetao 我这边得到的答复是：在android 低版本上可以与微信共享，但是高版本，随着系统对安全的加强，一般都会是下载自己的内核。

另外：

1、重新安装会重新下载，覆盖安装不会重新下载内核。

2、本项目0.3.x使用的是静态方案，打包内核进去了，可以只打包一种abi，减小体积。

希望上述信息能帮到你。如有相关改进，欢迎pr

**Comment by haohetao** [comment]
@liuxiaoy 
谢谢回复，我的测试中高版本确实没法与微信共享，但是低版本在首次启动时加个sleep能提高首次加载成功率,500ms的延迟就可以，因为首次启动时x5初始化(即使是共享微信内核)需要时间。

**Comment by liuxiaoy** [comment]
@haohetao 你觉得有需要，你可以先本地尝试下，看看效果，功能ok的话可以的话再提个pr给我，我会把这个版本放到npm上
